name: we_slide
description: A Flutter package which implements a backdrop displaying contextual and actionable content. =]
version: 1.0.2
homepage: https://github.com/luciano-work/we_slide

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.0
flutter: